name: 'Create Internal Meta'

on:
  workflow_dispatch:

env:
  AWS_RELEASE_ACCESS_KEY_ID: ${{secrets.AWS_RELEASE_ACCESS_KEY_ID}}
  AWS_RELEASE_SECRET_ACCESS_KEY: ${{secrets.AWS_RELEASE_SECRET_ACCESS_KEY}}
    
jobs:
  win64:
    name: 'Windows 64-bit'
    runs-on: windows-latest
    strategy:
      matrix:
        ReleaseName: [release]
        include:
          - ReleaseName: release
            ReleaseConfig: RelWithDebInfo
    env:
      OS_TAG: "win64"
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cloudflare CLI
        run: npm install -g cloudflare-cli
        
      - name: Run script
        run: powershell -File ./ci/internal_meta.ps1
