name: 'CI Build 28.1.1'

on:
  workflow_dispatch:

env:
  SL_OBS_VERSION: "28.1.1"
  SLGenerator: Visual Studio 17 2022
  GRPC_VERSION: v1.58.0
  AWS_SYMB_ACCESS_KEY_ID: ${{secrets.AWS_SYMB_ACCESS_KEY_ID}}
  AWS_SYMB_SECRET_ACCESS_KEY: ${{secrets.AWS_SYMB_SECRET_ACCESS_KEY}}
  RELEASE_BUCKET: "obsstudionodes3.streamlabs.com"
    
jobs:
  win64:
    name: 'Windows 64-bit'
    runs-on: windows-latest
    strategy:
      matrix:
        ReleaseName: [release]
        include:
          - ReleaseName: release
            ReleaseConfig: RelWithDebInfo
    env:
      OS_TAG: "win64"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
         
      - name: Run build script
        run: powershell -File ./ci/pipeline.ps1 "${{ github.workspace }}" "${{ github.sha }}"
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_RELEASE_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_RELEASE_SECRET_ACCESS_KEY}}
          aws-region: us-west-2
          
      - name: Deploy
        run: aws s3 cp slplugin-${{env.SL_OBS_VERSION}}-${{ github.sha }}.7z s3://${{env.RELEASE_BUCKET}} --acl public-read
