name: 'CI Build'

on:
  workflow_dispatch:

env:
  SLGenerator: Visual Studio 17 2022
  GRPC_VERSION: v1.47.0

jobs:
  win64:
    name: 'Windows 64-bit'
    runs-on: windows-latest
    strategy:
      matrix:
        ReleaseName: [release]
        include:
          - ReleaseName: release
            ReleaseConfig: RelWithDebInfo
    env:
      OS_TAG: "win64"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Define gRPC_DIR
        run: |
          echo "Protobuf_DIR=${{ github.workspace }}\..\grpc_dist\cmake" >> $GITHUB_ENV
          echo "absl_DIR=${{ github.workspace }}\..\grpc_dist\lib\cmake\absl" >> $GITHUB_ENV
          echo "gRPC_DIR=${{ github.workspace }}\..\grpc_dist\lib\cmake\grpc" >> $GITHUB_ENV
         
      - name: Run build script
        run: powershell -File ./ci/pipeline.ps1
