name: 'OBS Symbols'

on:
  workflow_dispatch:

env:
  AWS_SYMB_ACCESS_KEY_ID: ${{ secrets.AWS_SYMB_ACCESS_KEY_ID }}
  AWS_SYMB_SECRET_ACCESS_KEY: ${{ secrets.AWS_SYMB_SECRET_ACCESS_KEY }}
    
jobs:
  win64:
    name: 'Windows 64-bit'
    runs-on: windows-latest
    env:
      OS_TAG: "win64"
      ReleaseName: release
      ReleaseConfig: RelWithDebInfo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
         
      - name: Run obs symbol 30.1.1
        run: powershell -File ./ci/obs_symbols.ps1 "${{ github.workspace }}" "https://cdn-fastly.obsproject.com/downloads/OBS-Studio-30.1.1-Full-Installer-x64.exe"
         