name: 'Publish'

on:
  workflow_dispatch:

env:
  SL_OBS_VERSION: ${{ github.ref_name }}
  SLGenerator: Visual Studio 17 2022
  AWS_RELEASE_ACCESS_KEY_ID: ${{secrets.AWS_RELEASE_ACCESS_KEY_ID}}
  AWS_RELEASE_SECRET_ACCESS_KEY: ${{secrets.AWS_RELEASE_SECRET_ACCESS_KEY}}
    
jobs:
  publish:
    name: 'Publish'
    runs-on: windows-latest
    strategy:
      matrix:
        ReleaseName: [release]
        include:
          - ReleaseName: release
            ReleaseConfig: RelWithDebInfo
    env:
      OS_TAG: "win64"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cloudflare CLI
        run: npm install -g cloudflare-cli
                 
      - name: Run publish script
        env:
          CF_API_EMAIL: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}
          CF_API_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
        run: powershell -File ./ci/release.ps1 "${{ github.workspace }}" "${{ github.sha }}"
